<?php

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('items')->insert([
            ['item_name'=>  'Item1','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item2','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item3','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item4','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item5','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item6','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item7','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item8','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item9','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item10','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item11','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item12','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item13','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item14','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item15','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item16','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item17','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item18','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item19','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item20','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item21','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item22','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item23','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item24','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item25','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item26','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item27','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item28','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item29','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item30','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item31','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item32','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item33','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item34','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item35','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item36','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item37','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item38','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item39','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item40','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item41','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item42','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item43','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item44','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item45','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item46','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item47','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item48','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item49','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item50','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item51','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item52','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item53','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item54','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item55','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item56','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item57','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item58','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item59','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item60','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item61','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item62','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item63','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item64','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item65','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item66','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item67','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item68','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item69','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item70','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item71','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item72','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item73','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item74','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item75','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item76','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item77','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item78','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item79','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item80','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item81','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item82','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item83','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item84','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item85','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item86','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item87','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item88','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item89','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item90','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item91','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item92','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item93','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item94','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item95','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item96','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item97','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item98','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item99','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item100','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item101','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item102','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item103','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item104','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item105','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item106','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item107','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item108','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item109','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item110','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item111','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item112','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item113','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item114','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item115','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item116','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item117','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item118','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item119','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item120','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item121','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item122','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item123','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item124','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item125','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item126','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item127','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item128','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item129','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item130','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item131','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item132','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item133','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item134','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item135','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item136','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item137','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item138','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item139','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item140','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item141','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item142','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item143','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item144','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item145','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item146','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item147','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item148','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item149','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item150','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item151','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item152','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item153','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item154','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item155','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item156','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item157','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item158','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item159','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item160','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item161','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item162','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12'],
            ['item_name'=>  'Item163','description' => 'migration is here','size' => 'big','cost_price'=>'5620','selling_price' => '9546','quantity' => '12']


        ]);
    }
}
